<?php

/**
 * Return an array containing the available hashes
 * @return array
 */
function _ldap_passwords_hashes() {
    return array ('crypt' => 'crypt', 'SHA-1' => 'SHA-1', 'MD5' => 'MD5');
}


/**
 * Returns the selected hash algorithm specified by _ldap_passwords_hashes().
 * @return string
 */
function _ldap_passwords_hash() {
    return variable_get('ldappwd_hash', 'SHA-1');
}

/**
 * Returns if spaces in group and user names shall be removed
 * @return bool
 */
function _ldap_passwords_names_without_whitespace() {
    return variable_get('ldappwd_names_without_whitespace', true);
}


/**
 * Returns if groups and user names shall be exported lowercase
 * @return bool
 */
function _ldap_passwords_names_lowercase() {
    return variable_get('ldappwd_names_lowercase', true);
}


/**
 * Sanatizes the user name to be htpasswd conform. Removes ":" character as it
 * may cause trouble in the files. All non-word characters are removed to
 * be htpasswd/htgroup compliant.
 * @param string $name
 * @return string
 */
function _ldap_passwords_sanatize_name($name) {
    $name = trim(preg_replace('/[^\w\s]/i', '', $name), " \t\n\r");
    if(_ldap_passwords_names_without_whitespace()) $name = str_replace(' ','', $name);
    if(_ldap_passwords_names_lowercase()) $name = strtolower($name);
    return $name;
}


/**
 * Returns the password hashed according to users preferences
 * @param string $password
 * @return string
 */
function _ldap_passwords_crypt($password) {
    $hashes = _ldap_passwords_hashes();
    switch ($hashes[_ldap_passwords_hash()]) {
        case 'crypt':
            return crypt($password, chr(rand(65, 122)) . chr(rand(65, 122)));
            break;
        case 'SHA-1':
            return '{SHA}' . base64_encode(sha1($password, TRUE));
            break;
        case 'MD5':
            return '{MD5}' . base64_encode(MD5($password, TRUE));
        default:
            return _ldap_passwords_hash();
    }
}

/**
 * Update htpassword table with the new password of the user
 * @param object $edit
 * @return void
 */
function _ldap_passwords_update($edit) {
    if(isset($edit->pass) && $edit->pass != '' && isset($edit->name) && strlen(trim($edit->name)) > 0) {
        $user = $edit->name;
        $pass = _ldap_passwords_crypt($edit->pass);
        $passwds[$user] = $pass;
        if(isset($edit->uid) && $edit->uid > 0) {
            $ref_user = user_load($edit->uid);
            if($ref_user->name != $user) {
                db_query("DELETE FROM {ldap_users} WHERE username = :username", array(':username' => $ref_user->name));
            }
        }
        db_query("DELETE FROM {ldap_users} WHERE username = :user", array(':user' => $user));
        db_query("INSERT INTO {ldap_users} (uid, username, passwd) VALUES(:uid, :user, :pass)", array(':uid' => $edit->uid, ':user' => $user, ':pass' => $pass));
    }
}

/**
 * Remove the one user for the htpassword file
 * @param string $username
 * @return void
 */
function _ldap_passwords_delete_user($username) {
    db_query("DELETE FROM {ldap_users} WHERE username = :username", array(':username' => $username));
    db_query("INSERT INTO {ldap_users} (username, passwd) VALUES(:username, :passwd)", array(':username' => $username, ':passwd' => "****DELETED") );
}


/**
 * Remove the user for the htpassword file
 * @param object $account
 * @return void
 */
function _ldap_passwords_delete($account) {
    _ldap_passwords_delete_user($account->name);
}


/**
 * User cancel hook
 * @param array $edit
 * @param object $account
 * @param string $method
 * @return void
 */
function ldap_passwords_user_cancel($edit, $account, $method) {
    _ldap_passwords_delete($account);
}


/**
 * User delete hook
 * @param object $account
 * @return void
 */
function ldap_passwords_user_delete($account) {
    _ldap_passwords_delete($account);
}


/**
 * User insert/edit hook. Used instead of ldap_passwords_user_insert() and
 * ldap_passwords_user_update() because at these states the password is already
 * hashed.
 * @param string $entity_type
 * @param object $entity
 * @param array $form
 * @param array $form_state
 * @return void
 */
function ldap_passwords_field_attach_submit($entity_type, $entity, $form, &$form_state) {
    if($entity_type != 'user') return;
    if(!empty($entity->name) && !empty($entity->pass)) {
        $r = reset(db_query('SELECT pass FROM {users} WHERE uid=:uid', array(':uid' => $entity->uid))->fetchCol());
        if($r != $entity->pass) {
            _ldap_passwords_update($entity);
        }
    }
}


/**
 * Role delete hook
 * @param object $role
 * @return void
 */
function ldap_passwords_user_role_update($role) {
    //_ldap_passwords_updategroup();
}


/**
 * Role delete hook
 * @param object $role
 * @return void
 */
function ldap_passwords_user_role_delete($role) {
    //_ldap_passwords_updategroup();
}


/**
 * Returns help and module information
 * @param string $path which path of the site we're displaying help
 * @param array $arg Holds the current path as would be returned from arg() function
 * @return string
 */
function ldap_passwords_help($path, $arg) {
    if($path != 'admin/help#ldap_passwords') return '';
    return '<pre>' . htmlspecialchars(@file_get_contents(dirname(__FILE__) . '/README.txt'), null, 'UTF-8') . '</pre>';
}


/**
* Returns the required permissions for the ldap_passwords module
* @return array
*/
function ldap_passwords_permission() {
    return array(
        'administer ldap_passwords' => array(
            'title' => t('Administer LDAP login details export'),
            'restrict access' => true
        )
    );
}


/**
 * Administration menu entry
 * @return array
 */
function ldap_passwords_menu() {
    $items = array();
    $items['admin/config/people/ldap_passwords'] = array(
        'title' => 'LDAP login details export',
        'description' => 'Preferences for the LDAP login details export module',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('ldap_passwords_admin_form'),
        'access arguments' => array('administer ldap_passwords'),
    );
    return $items;
}


/**
 * Returns the configuration form structure
 * @return array
 */
function ldap_passwords_admin_form() {
    $form['ldappwd_hash'] = array(
        '#type' => 'radios',
        '#title' => t('password hashing algorythm'),
        '#description' => t("How shall the password be hashed (crypt only available for unix, SHA1 can be used on all platforms)"),
        '#options' => _ldap_passwords_hashes(),
        '#default_value' => _ldap_passwords_hash(),
    );
    $form['ldappwd_names_lowercase'] = array(
        '#type' => 'checkbox',
        '#title' => t('Export user names and group names lowercase'),
        '#description' => t("If yes, ldap_passwords will export the lowercase user names (e.g. 'User' will be exported as 'user'). Groups will always be exported lowercase (as the user does not need to enter a group, so this makes it easier to design the .htaccess files). Caution: this option may increase the file size of the htuser file."),
        '#default_value' => _ldap_passwords_names_lowercase(),
    );
    $form['ldappwd_names_without_whitespace'] = array(
        '#type' => 'checkbox',
        '#title' => t('Remove whitespaces in user names and groups'),
        '#description' => t("If yes, ldap_passwords will remove all whitespaces in user names and groups (e.g. 'User 1' will be exported as 'User1'). Caution: this increases the file size of the htuser file. If you use groups, then you must check this setting because whitespaces are used as separators in the group file. This setting goes along with the checkbox above."),
        '#default_value' => _ldap_passwords_names_without_whitespace(),
    );

    // Small description ...
    $notewhitespaces = _ldap_passwords_names_lowercase() ? " Enter your login name without whitespaces and special characters." : "";

    return system_settings_form($form);
}


/**
 * Form validation callback. Checks if htpasswd/htgroup file are writable
 * @param array $form
 * @param array& $form_state
 * @return void
 */
function ldap_passwords_admin_form_validate($form, &$form_state) {
    $error = false;
}

/**
 * Cron hook
 * @return void
 */
function ldap_passwords_cron() {
    db_query('DELETE FROM {ldap_users} WHERE username NOT IN (SELECT name from {users})');
}
?>
