<?php

/**
 * Implements hook_cron().
 */
function reactos_cron() {
  $svn_path = '/srv/www';
  exec('svn update ' . $svn_path . ' | tail', $output);
  watchdog('ReactOS', "Command 'svn up' attempted. The tail of the output follows: <br><em>!output</em>", array('!output' => $output[0]));
}

/**
 * SVN functions for subsystems
 */
function reactos_GetLatestRevision()
{
	$fp = fopen("http://svn.reactos.org/svnact/svn_activity.xml", "r");
		
	do
	{
		$line = fread($fp, 1024);

		$firstpos = strpos($line, "<id>");
			
		if($firstpos > 0)
		{
			$lastpos = strpos($line, "</id>");
			return substr($line, $firstpos + 4, ($lastpos - $firstpos - 4));
		}
	} while($line);
		
	fclose($fp);
}
  